Gossip_Project_avec_du_front-master/config/routes.rb
Rails.application.routes.draw do
  root "gossips#index"

  get "/static_pages/team", to: "static_pages#team"

  get "/static_pages/contact", to: "static_pages#contact"

  get "/welcome/:name", to: "welcome#user", as: "welcome"

  get "/gossips/:id", to: "gossips#show", as: "gossips"

  get "/user_profile/:id", to: "user_profile#show", as: "user_profile"
end

Gossip_Project_avec_du_front-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Gossip_Project_avec_du_front-master/app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

Gossip_Project_avec_du_front-master/app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossips_tags
  has_many :tags, through: :gossips_tags
  has_many :comments
end

Gossip_Project_avec_du_front-master/app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

Gossip_Project_avec_du_front-master/app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

Gossip_Project_avec_du_front-master/app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossips_tags
  has_many :gossips, through: :gossips_tags
end

Gossip_Project_avec_du_front-master/app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: "sender_id", class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: "recipient_id", class_name: "PrivateMessage"
  has_many :comments

  def full_name
    full_name = self.first_name + " " + self.last_name
    return full_name
  end
end

Gossip_Project_avec_du_front-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Gossip_Project_avec_du_front-master/app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def show
    @gossip = Gossip.find(params[:id])
  end

  def index
  end
end

Gossip_Project_avec_du_front-master/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def team
  end

  def contact
  end
end

Gossip_Project_avec_du_front-master/app/controllers/user_profile_controller.rb
class UserProfileController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

Gossip_Project_avec_du_front-master/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def user
  end
end

Gossip_Project_avec_du_front-master/app/helpers/application_helper.rb
module ApplicationHelper
end

Gossip_Project_avec_du_front-master/app/helpers/gossips_helper.rb
module GossipsHelper
end

Gossip_Project_avec_du_front-master/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

Gossip_Project_avec_du_front-master/app/helpers/user_profile_helper.rb
module UserProfileHelper
end

Gossip_Project_avec_du_front-master/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Gossip_Project_avec_du_front-master/app/views/gossips/index.html.erb
<h1 class="ml-2">XOXO, Gossip Bot !</h1>
<p class="ml-2">Voici la liste de tous les potins envoyés par nos utilisateurs :</p>
<div class="container">
  <div class="row">
    <% Gossip.all.each do |gossip| %>

      <div class="card col-4 gossip-card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= gossip.title%></h5>
          <p class="card-text"><%= gossip.content%></p>
          <%= link_to "Voir le Gossip", gossips_path(gossip.id), class: "btn btn-primary" %>
        </div>
      </div>

    <% end %>
  </div>
</div>

Gossip_Project_avec_du_front-master/app/views/gossips/show.html.erb
<h1>POTIN N°<%= params[:id]%></h1>
<div class="ml-2">
  <p><span class="attribute">Auteur: </span>
    <%= @gossip.user.full_name %></p>
  <p><span class="attribute">Titre: </span>
    <%= @gossip.title %></p>
  <p><span class="attribute">Contenu</span>
    <%= @gossip.content %></p>
  <p><span class="attribute">Date de création: </span>
    <%= I18n.l(@gossip.created_at, format: :long) %></p>

  <%= link_to "Voir le profil de #{@gossip.user.full_name}", user_profile_path(@gossip.user_id)%>
</div>

Gossip_Project_avec_du_front-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400;700&display=swap" rel="stylesheet">
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <%= link_to "Accueil", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <%= link_to "Team", static_pages_team_path, class: "nav-item nav-link" %>
            <%= link_to "Contact", static_pages_contact_path, class: "nav-item nav-link" %>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

Gossip_Project_avec_du_front-master/app/views/static_pages/contact.html.erb
<h1>Contactez-nous ! &#x1F43C; </h1>

<p>jaiungossip@gossipbot.com</p>

Gossip_Project_avec_du_front-master/app/views/static_pages/team.html.erb
<h1>Voici la team &#x1F43C; </h1>

<p><span class="attribute">Prénom: </span> Gossip</p>
<p><span class="attribute">Nom: </span> Bot</p>
<p><span class="attribute">Ville de résidence: </span> NYC Babyyy</p>

Gossip_Project_avec_du_front-master/app/views/user_profile/show.html.erb
<h1>Profil de <%= @user.full_name%></h1>
<div class="ml-2">
  <p><span class="attribute">Prénom: </span>
    <%= @user.first_name %></p>
  <p><span class="attribute">Nom: </span>
    <%= @user.last_name %></p>
  <p><span class="attribute">Email: </span>
    <%= @user.email %></p>
  <p><span class="attribute">Ville de résidence: </span>
    <%= @user.city.name %></p>
  <p><span class="attribute">Description: </span>
    <%= @user.description %></p>
</div>

Gossip_Project_avec_du_front-master/app/views/welcome/user.html.erb
<h1>BIENVENUE <%= params[:name]%> !</h1>
<p>Ici c'est notre super site de potins, il est chouette, non ?</p>